version: '2'

services:
  jira:
    image: blacklabelops/jira
    container_name: jirasoftware
    networks:
      - jiranet
    volumes:
      - jiradata:/var/atlassian/jira
    ports:
      - '80:8080'
    environment:
      - 'JIRA_DATABASE_URL=oracle://jira@oracle/jiradb'
      - 'JIRA_DB_PASSWORD=jellyfish'
      - 'CATALINA_OPTS= -Xms256m -Xmx1g'
      - 'JIRA_PROXY_NAME='
      - 'JIRA_PROXY_PORT='
      - 'JIRA_PROXY_SCHEME='
      - 'DOCKER_WAIT_HOST=oracle-xe-11g'
      - 'DOCKER_WAIT_PORT=5432'
    links:
      - 'oracle:oracle-xe-11g'
    labels:
      com.blacklabelops.description: "Atlassian Jira"
      com.blacklabelops.service: "jira"

  oracle:
    image: alexeiled/docker-oracle-xe-11g
    hostname: oracle-xe-11g
    mem_min: 400m
    ports:
      - 1521:1521
      - 8999:8080
    networks:
      - jiranet
    volumes:
      - .oracle_data:/u01/app/oracle
    environment:
      - 'ORACLE_USER=jira'
      # CHANGE THE PASSWORD!
      - 'ORACLE_PASSWORD=jellyfish'
      - 'ORACLE_DB=jiradb'
      - 'ORACLE_ENCODING=UNICODE'
      - 'ORACLE_HOME=/u01/app/oracle/product/11.2.0/xe'
      - 'PATH=$ORACLE_HOME/bin:$PATH'
      - 'ORACLE_SID=XE'
      - 'ORACLE_ALLOW_REMOTE=true'
    labels:
      com.alexeiled.description: "Oracle XE 11g Database Server"
      com.alexeiled.service: "oracle-xe-11g"

volumes:
  jiradata:
    external: false
  postgresqldata:
    external: false

networks:
  jiranet:
    driver: bridge
